name: .NET 7 CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        name: Setup .NET 5.0 SDK
        with:
          dotnet-version: '5.0.x'
      - uses: actions/setup-dotnet@v3
        name: Setup .NET 6.0 SDK
        with:
          dotnet-version: '6.0.x'
      - uses: actions/setup-dotnet@v3
        name: Setup .NET 7.0 SDK
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build Ninject.Extensions.DependencyInjection.sln -c Release
      - name: Test
        run: dotnet test Ninject.Extensions.DependencyInjection.sln -c Release
